before_script: 
    - cat /etc/os-release
    - apt update -qy
    - apt install -y gfortran libblas-dev liblapack-dev 
    

python-36:
    image: python:3.6
    script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - make test
