before_script: 
    - cat /etc/os-release
    - apt update -qy
    - apt install -y gfortran libblas-dev liblapack-dev 
    

python-36:
    script:
        image: python:3.6
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - make test
