sudo: false
language: python
python:
  - "3.6"
  - "3.7"
cache: apt
addons:
   apt:
      packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

before_install:
  - lsb_release -a
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - #conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest pytest-cov hypothesis mock
  - pip install pep8 python-coveralls
  - pip install --upgrade coverage
script:
  - make test
after_success:
  - coveralls
